name: Test and Review python workflow
on: push
jobs:
  job_python:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the Code
        uses: actions/checkout@v7
      - name: Setup Python
        uses: actions/setup-python@v7
        with:
          python-version: '3.13'
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirement.txt
      - name: Run Test
        run: |
          pytest test
      
        
